<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <DebugType>full</DebugType>
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.0-beta1" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.0-beta1" />
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.2.0-beta1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.0-beta1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.0-beta1" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.0-beta1" />
        <PackageReference Include="AvaloniaColorPicker" Version="1.4.0" />
        <PackageReference Include="FluentAvaloniaUI" Version="2.1.0" />
        <PackageReference Include="Material.Avalonia" Version="3.7.3-nightly.0.2" />
        <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="4.0.0-beta.24360.3" />
    </ItemGroup>


    <ItemGroup>
        <AdditionalFiles Include="**\*.xaml" />
    </ItemGroup>
    
    <ItemGroup>
      <None Remove="Xamlade.png" />
      <None Remove="Avalonia.AXAML.LanguageServer.Log20231031.txt" />
      <None Remove="googleca45d2d676594602.html" />
      <None Remove="index.html" />
      <None Remove="Xamlade2.png~" />
      <None Remove="Xamlade2.png" />
      <None Remove="qodana.yaml" />
    </ItemGroup>


    <ItemGroup>
      <AvaloniaXaml Remove="TestWindow.axaml" />
      <AvaloniaXaml Remove="ComboboxStyle.axaml" />
    </ItemGroup>


    <ItemGroup>
      <Compile Remove="TestWindow.axaml.cs" />
      <Compile Remove="IgnoredTypeConverter.cs" />
      <Compile Remove="IgnTypeConverter.cs" />
      <Compile Update="[TODO]Unstructed\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Include="bin\Debug\net9.0\XamladeDemo\App.axaml.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\MainWindow.axaml.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.AssemblyInfo.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.AssemblyInfo.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.AssemblyInfo.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\Program.cs" />
    </ItemGroup>


    <ItemGroup>
      <None Remove="RES\loading.gif" />
      <AvaloniaResource Include="RES\loading.gif" />
    </ItemGroup>


    <ItemGroup>
      <Reference Include="Avalonia.Gif">
        <HintPath>Avalonia.GIF\Avalonia.Gif.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
        <!-- Добавление всех файлов из папки assets в ресурсы -->
        <AvaloniaResource Include="assets\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AvaloniaResource>
    </ItemGroup>

    <ItemGroup>
        <MySourceFiles Include="assets\**\*.*" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="bin\Debug\net9.0\XamladeDemo\.idea\.idea.XamladeDemo\.idea\.gitignore" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\.idea\.idea.XamladeDemo\.idea\avalonia.xml" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\.idea\.idea.XamladeDemo\.idea\indexLayout.xml" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\.idea\.idea.XamladeDemo\.idea\projectSettingsUpdater.xml" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\.idea\.idea.XamladeDemo\.idea\vcs.xml" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\.idea\.idea.XamladeDemo\.idea\workspace.xml" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\App.axaml" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\App.axaml1" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\app.manifest" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\-4sG5ytVcL4.jpg" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\debug.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\debug.png.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\debug.png1.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\debug.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\debug1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\debug1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\dexamlize.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\dexamlize.png.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\dexamlize.png1.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\dexamlize.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\dexamlize1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\dexamlize1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\fuck.jpg" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Icon.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Icon.png.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Icon.png1.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Icon.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Icon1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Icon1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\import-export.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\import-export1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\photo_2021-12-13_00-44-53.jpg" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\redo.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\redo.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\redo1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\redo1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\remove.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\remove.png.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\remove.png1.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\remove.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\remove1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\remove1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\run.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\run.png.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\run.png1.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\run.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\run1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\run1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\settings.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\settings.png.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\settings.png1.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\settings.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\settings1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\settings1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\shelved.patch" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\undo.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\undo.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\undo1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\undo1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade_logo.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade_logo1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade_logo_2.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade_logo_2.png.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade_logo_2.png1.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade_logo_2.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade_logo_21.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Xamlade_logo_21.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\xamlize.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\xamlize.png.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\xamlize.png1.kra" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\xamlize.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\xamlize1.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\xamlize1.png~" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Снимок экрана_2023-11-11_04-09-11.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\assets\Снимок экрана_2024-04-17_00-51-19.png" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\Avalonia.AXAML.LanguageServer.Log20240721.txt" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\Avalonia.AXAML.LanguageServer.Log20240731.txt" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\Avalonia.AXAML.LanguageServer.Log20240907.txt" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\BUILD.sh" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\global.json" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\MainWindow.axaml" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\MainWindow.axaml1" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\apphost" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\Avalonia\original.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\Avalonia\original.pdb" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\Avalonia\original.ref.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\Avalonia\references" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\Avalonia\resources" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\Avalonia\Resources.Inputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\refint\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\ref\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.AssemblyInfoInputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.assets.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.csproj.AssemblyReference.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.csproj.CopyComplete" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.csproj.CoreCompileInputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.csproj.FileListAbsolute.txt" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.GeneratedMSBuildEditorConfig.editorconfig" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.genruntimeconfig.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.pdb" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\apphost" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\Avalonia\original.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\Avalonia\original.pdb" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\Avalonia\original.ref.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\Avalonia\references" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\Avalonia\resources" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\Avalonia\Resources.Inputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\refint\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\ref\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.AssemblyInfoInputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.assets.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.csproj.AssemblyReference.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.csproj.CopyComplete" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.csproj.CoreCompileInputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.csproj.FileListAbsolute.txt" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.GeneratedMSBuildEditorConfig.editorconfig" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.genruntimeconfig.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.pdb" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.sourcelink.json" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\apphost" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\Avalonia\original.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\Avalonia\original.pdb" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\Avalonia\original.ref.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\Avalonia\references" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\Avalonia\resources" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\Avalonia\Resources.Inputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\refint\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\ref\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeD.0398BAED.Up2Date" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.AssemblyInfoInputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.assets.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.csproj.AssemblyReference.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.csproj.CoreCompileInputs.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.csproj.FileListAbsolute.txt" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.dll" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.GeneratedMSBuildEditorConfig.editorconfig" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.genruntimeconfig.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.pdb" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.sourcelink.json" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\project.assets.json" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\project.nuget.cache" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\project.packagespec.json" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\rider.project.model.nuget.info" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\rider.project.restore.info" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\XamladeDemo.csproj.nuget.dgspec.json" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\XamladeDemo.csproj.nuget.g.props" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\obj\XamladeDemo.csproj.nuget.g.targets" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\README.md" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\RUN.sh" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\XamladeDemo.csproj" />
      <Content Include="bin\Debug\net9.0\XamladeDemo\XamladeDemo.sln" />
    </ItemGroup>
    
    <Target Name="CopyAssets" BeforeTargets="Build">
        <MakeDir Directories="$(OutputPath)\assets" />
        <Copy SourceFiles="@(MySourceFiles)" DestinationFolder="$(OutputPath)\assets" SkipUnchangedFiles="true" />
    </Target>

</Project>
