<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Metalama>true</Metalama>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaNameGeneratorIsEnabled>false</AvaloniaNameGeneratorIsEnabled>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <DebugType>full</DebugType>
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.0-beta1" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.0-beta1" />
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.2.0-beta1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.0-beta1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.0-beta1" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.0-beta1" />
        <PackageReference Include="AvaloniaColorPicker" Version="1.4.0" />
        <PackageReference Include="FluentAvaloniaUI" Version="2.1.0" />
        <PackageReference Include="Material.Avalonia" Version="3.7.3-nightly.0.2" />
        <PackageReference Include="Metalama.Compiler" Version="2024.2.13">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Metalama.Compiler.Sdk" Version="2024.2.13" />
        <PackageReference Include="Metalama.Extensions.Architecture" Version="2024.2.24" />
        <PackageReference Include="Metalama.Framework" Version="2024.2.24" />
        <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="4.0.0-beta.24360.3" />
    </ItemGroup>


    <ItemGroup>
        <AdditionalFiles Include="**\*.xaml" />
        <AdditionalFiles Remove="bin\Debug\net9.0\XamladeDemo\**" />
        <AdditionalFiles Remove="bin\Debug\**" />
        <AdditionalFiles Remove="bin\**" />
    </ItemGroup>
    
    <ItemGroup>
      <None Remove="Xamlade.png" />
      <None Remove="Avalonia.AXAML.LanguageServer.Log20231031.txt" />
      <None Remove="googleca45d2d676594602.html" />
      <None Remove="index.html" />
      <None Remove="Xamlade2.png~" />
      <None Remove="Xamlade2.png" />
      <None Remove="qodana.yaml" />
      <None Remove="bin\Debug\net9.0\XamladeDemo\**" />
      <None Remove="bin\Debug\**" />
      <None Remove="bin\**" />
    </ItemGroup>


    <ItemGroup>
      <AvaloniaXaml Remove="TestWindow.axaml" />
      <AvaloniaXaml Remove="ComboboxStyle.axaml" />
      <AvaloniaXaml Remove="bin\Debug\net9.0\XamladeDemo\**" />
      <AvaloniaXaml Remove="bin\Debug\**" />
      <AvaloniaXaml Remove="bin\**" />
    </ItemGroup>


    <ItemGroup>
      <Compile Remove="TestWindow.axaml.cs" />
      <Compile Remove="IgnoredTypeConverter.cs" />
      <Compile Remove="IgnTypeConverter.cs" />
      <Compile Update="[TODO]Unstructed\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Include="bin\Debug\net9.0\XamladeDemo\App.axaml.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\MainWindow.axaml.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net7.0\XamladeDemo.AssemblyInfo.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net8.0\XamladeDemo.AssemblyInfo.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\obj\Debug\net9.0\XamladeDemo.AssemblyInfo.cs" />
      <Compile Include="bin\Debug\net9.0\XamladeDemo\Program.cs" />
      <Compile Remove="bin\Debug\net9.0\XamladeDemo\**" />
      <Compile Remove="bin\Debug\**" />
      <Compile Remove="bin\**" />
    </ItemGroup>


    <ItemGroup>
      <None Remove="RES\loading.gif" />
      <AvaloniaResource Include="RES\loading.gif" />
      <AvaloniaResource Remove="bin\Debug\net9.0\XamladeDemo\**" />
      <AvaloniaResource Remove="bin\Debug\**" />
      <AvaloniaResource Remove="bin\**" />
    </ItemGroup>


    <ItemGroup>
      <Reference Include="Avalonia.Gif">
        <HintPath>Avalonia.GIF\Avalonia.Gif.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
        <!-- Добавление всех файлов из папки assets в ресурсы -->
        <AvaloniaResource Include="assets\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AvaloniaResource>
    </ItemGroup>

    <ItemGroup>
        <MySourceFiles Include="assets\**\*.*" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="bin\Debug\net9.0\XamladeDemo\**" />
      <EmbeddedResource Remove="bin\Debug\**" />
      <EmbeddedResource Remove="bin\**" />
    </ItemGroup>
    
    <Target Name="CopyAssets" BeforeTargets="Build">
        <MakeDir Directories="$(OutputPath)\assets" />
        <Copy SourceFiles="@(MySourceFiles)" DestinationFolder="$(OutputPath)\assets" SkipUnchangedFiles="true" />
    </Target>

</Project>
